export const ALIASES = {
  "AB": "Andreas Bech Pedersen",
  "AVP": "Ane Vestergaard Pedersen",
  "AV": "Anne Valsted",
  "AO": "Astrid Sun Otte",
  "BPO": "Bjarne Poulsen",
  "BS": "Bo Serritzlew",
  "CM": "Carsten Søe Mortensen",
  "DH": "Dennis Horn",
  "DC": "Dorthe Corneliussen Bertelsen",
  "EB": "Emil Egetoft Brinch",
  "ENI": "Emil Nielsen",
  "HM": "Henrik Marcussen",
  "IC": "Ida Søttrup Christensen",
  "IS": "Inge Johansen Stuhr",
  "JG": "Jakob Mols Græsborg",
  "JH": "Jens H. Noe",
  "JL": "Jesper Laubjerg",
  "KB": "Kathrine Spandet Brøndum",
  "KH": "Kenneth Hald",
  "KVS": "Kristoffer Vorre Sørensen",
  "LGN": "Laura Guldbæk Nymann",
  "MTI": "Magnus Tolborg Ibsen",
  "MT": "Maria Rosborg Thornval",
  "MO": "Marianne Brun Ottesen",
  "MV": "Mark Vestergaard Pedersen",
  "MG": "Martin Gregersen",
  "MS": "Mia Mejlby Sørensen",
  "MTP": "Mikkel Tejlgaard Pedersen",
  "MM": "Måns Patrik Mårtensson",
  "RB": "Randi Borum",
  "RD": "Rasmus Damsgaard",
  "RA": "Rebecka Antonsen",
  "SG": "Sara Maiken Mols Græsborg",
  "SMB": "Stine Maria Birkeholm",
  "SNV": "Stine Nielsen Vad",
  "SP": "Stinne Krogh Poulsen",
  "TH": "Trine Hedegaard Nielsen",
  "TIN": "Trine Isager Nielsen",
  "TK": "Trine Krogh Korneliussen",
  "VSI": "Viola Simonsen"
};
